import { useState, useEffect } from 'react';
import { getEvents, createEvent, updateEvent, deleteEvent } from '../api/config';
import { Button, Card, Input, Spinner, Toast, EmptyState, Badge } from '../components/UI';

export default function Events() {
  const [events, setEvents] = useState([]);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState('');
  const [toast, setToast] = useState(null);
  const [editingId, setEditingId] = useState(null);
  const [form, setForm] = useState({ name: '', duration: '' });
  const [formErrors, setFormErrors] = useState({});
  const [showForm, setShowForm] = useState(false);

  useEffect(() => { fetchEvents(); }, []);

  async function fetchEvents() {
    try {
      setLoading(true);
      const res = await getEvents();
      setEvents(res.data);
    } catch (e) {
      setError('Failed to load events. Is the backend running?');
    } finally {
      setLoading(false);
    }
  }

  function validate() {
    const errs = {};
    if (!form.name.trim()) errs.name = 'Name is required';
    if (!form.duration || isNaN(form.duration) || Number(form.duration) < 1) errs.duration = 'Valid duration required';
    setFormErrors(errs);
    return Object.keys(errs).length === 0;
  }

  async function handleSubmit() {
    if (!validate()) return;
    setSaving(true);
    try {
      const payload = { name: form.name, duration: Number(form.duration) }; // slug auto-generated by backend
      if (editingId) {
        const res = await updateEvent(editingId, payload);
        setEvents(events.map(e => e.id === editingId ? res.data : e));
        showToast('Event updated!', 'success');
      } else {
        const res = await createEvent(payload);
        setEvents([...events, res.data]);
        showToast('Event created!', 'success');
      }
      resetForm();
    } catch (e) {
      showToast(e.response?.data?.detail || 'Something went wrong', 'error');
    } finally {
      setSaving(false);
    }
  }

  async function handleDelete(id) {
    if (!confirm('Delete this event?')) return;
    try {
      await deleteEvent(id);
      setEvents(events.filter(e => e.id !== id));
      showToast('Event deleted', 'info');
    } catch {
      showToast('Failed to delete', 'error');
    }
  }

  function handleEdit(event) {
    setForm({ name: event.name, duration: String(event.duration) });
    setEditingId(event.id);
    setShowForm(true);
    setFormErrors({});
    window.scrollTo({ top: 0, behavior: 'smooth' });
  }

  function resetForm() {
    setForm({ name: '', duration: '' });
    setEditingId(null);
    setShowForm(false);
    setFormErrors({});
  }

  function showToast(message, type) {
    setToast({ message, type });
    setTimeout(() => setToast(null), 3500);
  }

  return (
    <div className="max-w-5xl mx-auto px-6 py-10">
      {toast && <Toast message={toast.message} type={toast.type} onClose={() => setToast(null)} />}

      {/* Header */}
      <div className="flex items-center justify-between mb-8">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">Event Types</h1>
          <p className="text-gray-500 text-sm mt-1">Manage your bookable meeting types</p>
        </div>
        <Button onClick={() => { setShowForm(!showForm); if (editingId) resetForm(); }}>
          {showForm && !editingId ? 'Cancel' : '+ New Event'}
        </Button>
      </div>

      {/* Form */}
      {showForm && (
        <Card className="p-6 mb-8 border-blue-100 bg-blue-50/30">
          <h2 className="text-base font-semibold text-gray-900 mb-5">
            {editingId ? 'Edit Event' : 'Create New Event'}
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-5">
            <Input
              label="Event Name"
              placeholder="e.g. 30 Min Call"
              value={form.name}
              onChange={e => setForm({ ...form, name: e.target.value })}
              error={formErrors.name}
            />
            <Input
              label="Duration (minutes)"
              type="number"
              placeholder="30"
              value={form.duration}
              onChange={e => setForm({ ...form, duration: e.target.value })}
              error={formErrors.duration}
            />
            <div className="flex flex-col gap-1.5">
              <label className="text-sm font-medium text-gray-700">Slug (auto-generated)</label>
              <div className="px-4 py-2.5 rounded-xl border border-gray-100 bg-gray-50 text-sm text-gray-400 italic">
                Generated automatically from event name
              </div>
            </div>
          </div>
          <div className="flex gap-3">
            <Button onClick={handleSubmit} loading={saving}>
              {editingId ? 'Update Event' : 'Create Event'}
            </Button>
            <Button variant="secondary" onClick={resetForm}>Cancel</Button>
          </div>
        </Card>
      )}

      {/* Content */}
      {loading ? (
        <Spinner />
      ) : error ? (
        <div className="bg-red-50 text-red-700 rounded-2xl p-6 text-sm border border-red-100">
          <strong>Error:</strong> {error}
        </div>
      ) : events.length === 0 ? (
        <EmptyState icon="📅" title="No events yet" description="Create your first event type to start accepting bookings." />
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {events.map(event => (
            <Card key={event.id} hover className="p-5">
              <div className="flex items-start justify-between mb-3">
                <div className="w-10 h-10 bg-blue-100 rounded-xl flex items-center justify-center">
                  <svg className="w-5 h-5 text-blue-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
                  </svg>
                </div>
                <Badge color="blue">{event.duration} min</Badge>
              </div>
              <h3 className="font-semibold text-gray-900 mb-1">{event.name}</h3>
              <p className="text-xs text-gray-400 font-mono mb-3">/{event.slug}</p>
              <div className="flex items-center gap-1.5 bg-blue-50 rounded-xl px-3 py-2 mb-3">
                <span className="text-xs text-blue-600 truncate flex-1 font-mono">/book/{event.slug}</span>
                <button
                  onClick={() => { navigator.clipboard.writeText(`http://localhost:3000/book/${event.slug}`); showToast('Link copied!', 'success'); }}
                  className="text-blue-500 hover:text-blue-700 flex-shrink-0 text-xs font-medium px-1"
                >
                  Copy
                </button>
              </div>
              <div className="flex gap-2 pt-3 border-t border-gray-50">
                <Button size="sm" variant="ghost" onClick={() => handleEdit(event)}>Edit</Button>
                <Button size="sm" variant="danger" onClick={() => handleDelete(event.id)}>Delete</Button>
                <a href={`/book/${event.slug}`} target="_blank" rel="noreferrer" className="inline-flex items-center px-3 py-1.5 text-xs font-medium rounded-xl text-blue-600 hover:bg-blue-50 transition-colors">Open ↗</a>
              </div>
            </Card>
          ))}
        </div>
      )}
    </div>
  );
}
