import axios from 'axios';

const BASE_URL = 'http://127.0.0.1:8000';

export const api = axios.create({
  baseURL: BASE_URL,
  headers: { 'Content-Type': 'application/json' },
});

// Events
export const getEvents = () => api.get('/events');
export const getEventBySlug = (slug) => api.get(`/events/slug/${slug}`);
export const createEvent = (data) => api.post('/events', data);   // slug is auto-generated by backend
export const updateEvent = (id, data) => api.put(`/events/${id}`, data);
export const deleteEvent = (id) => api.delete(`/events/${id}`);

// Availability
export const getAvailability = () => api.get('/availability');
export const createAvailability = (data) => api.post('/availability', data);
export const deleteAvailability = (id) => api.delete(`/availability/${id}`);

// Bookings
export const getSlots = (eventId, date) =>
  api.get(`/bookings/slots?event_id=${eventId}&selected_date=${date}`);
export const createBooking = (data) => api.post('/bookings', data);
export const getUpcomingBookings = () => api.get('/bookings/upcoming');
export const getPastBookings = () => api.get('/bookings/past');
export const cancelBooking = (id) => api.delete(`/bookings/${id}`);
